version: '3.1'
services:
  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: trololo
      POSTGRES_USER: app
      POSTGRES_DB: db